### ISSUE TITLE
[leo_storage] Unresponsive when Disk IO takes a long time

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#503]
## Description
`leo_storage` gets overloaded and becomes unresponsive under continuous workload.
Hence, requests from `leo_gateway` are not handled and thus client requests are blocked.

### Test Setup
* LeoFS Version: 1.3.1-dev
* OS: Ubuntu 14.04
* 5x Storage, SSD-backed
* 1x Gateway, No Cache

### Test Methodology
Continuously write images into LeoFS at a rate of 300MB/s [Test Report](https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.1/overload/20161024_image_f4m_load_rate200_overload_1)

### Observation
![picture1](https://cloud.githubusercontent.com/assets/360884/19917767/77aa00c8-a109-11e6-8f3e-356db02255db.png)
* After 1.5 minutes, throughput dropped to <50MB/s
* High IOWait at node08

### Logs
Info Log at node08, slow operations
```
[I]     S2@192.168.100.38       2016-10-24 11:25:17.121436 +0900        1477275917      leo_object_storage_event:handle_event/2 54      [{cause,"slow operation"},{mehtod,put},{key,<<"test/3342136">>},{processing_time,1050}]
[I]     S2@192.168.100.38       2016-10-24 11:25:20.141601 +0900        1477275920      leo_object_storage_event:handle_event/2 54      [{cause,"slow operation"},{mehtod,put},{key,<<"test/2904877">>},{processing_time,1260}]
[I]     S2@192.168.100.38       2016-10-24 11:25:21.605988 +0900        1477275921      leo_object_storage_event:handle_event/2 54      [{cause,"slow operation"},{mehtod,put},{key,<<"test/1404813">>},{processing_time,1460}]
```

**Comment by windkit** [comment]
## Further Analysis
### Object Timestamp
(Statistics gathered with `leofs-adm whereis` of entire key domain)

 Time | Number of Entries 
-------|---------------------
11:25:16 | 3957
11:25:17 | 18120
11:25:18 | 12144
11:25:19 | 0
11:25:20 | 0
11:25:21 | 2916
11:25:22 | 25464

Normally, there should be around 24,000 entries with 8,000 ops * 3 replicas.
Number of requests got processed dropped around the same time of the slow operations

**Comment by windkit** [comment]
## Further Analysis (Test with Processing Time Logging)
### Preparation
Processing Time is logged at `leo_gateway` and `leo_storage` to check the request flow

1. `leo_gateway` - Duration spent on put object request to `leo_storage` at `leo_gateway_rpc_handler:put`
2. `leo_storage` - Duration spent on processing request from `leo_gateway` and replication from `leo_storage` (self/remote)

### Latency Log
![image](https://cloud.githubusercontent.com/assets/360884/19917986/5fa27e90-a10b-11e6-841a-ac4b6c20088b.png)
[storage_info_trimmed.txt](https://github.com/leo-project/leofs/files/565778/storage_info_trimmed.txt)
[gateway_info_trimmed.txt](https://github.com/leo-project/leofs/files/565779/gateway_info_trimmed.txt)

### Monitor
![untitled](https://cloud.githubusercontent.com/assets/360884/19918010/8d652026-a10b-11e6-8734-323c967490f0.png)

### Summary
 - Write operations got delayed
 - Replication requests were queued
 - New requests were delayed
   - Long time (3s) in GW process
   - Very short time (1ms) in Storage process
 - RPC seemed to be stuck
   - entop showed similar delay (10ms -> 3s)

**Comment by windkit** [comment]
## Investigation
To find out the root cause of the problem

## Methodology
The process of storing an object in `leo_object_storage` involves two types of Disk IOs

1. Metadata Related (`leo_backend_db:put/get`)
2. Object Content (`file:pwrite` in `leo_object_storage_haystack:put`)

## Result
### Normal
![normal](https://cloud.githubusercontent.com/assets/360884/19998312/81d9a3ee-a2af-11e6-9757-5402483401bb.png)

### No Disk IO (Neither Metadata nor Content)
![nodiskio](https://cloud.githubusercontent.com/assets/360884/19998316/83de0a40-a2af-11e6-9902-9d6a6871ba18.png)

### No Content Write - Flat at 750 MB/s
![nodiskwrite](https://cloud.githubusercontent.com/assets/360884/19998321/8e6594ce-a2af-11e6-864f-077182133df7.png)

### No Metadata + No Seek - Flat at 750MB/s (Small Drops)
![nobackendb noseek](https://cloud.githubusercontent.com/assets/360884/19998320/8bc6eccc-a2af-11e6-96f0-b2a2ebc2f2b6.png)

### No Metadata - Flat at 750 MB/s (One Big Drop)
![nobackendb](https://cloud.githubusercontent.com/assets/360884/19998318/88be47dc-a2af-11e6-990e-5239d904549e.png)

**Comment by windkit** [comment]
## Investigation
Check if the backend db is a bottleneck

### Methodology
Relocate the backend DB to memory
```bash
$ mkdir /dev/shm/metadata
$ ln -s /dev/shm/metadata /ssd/avs/metadata
```

### Result
Stable Bandwidth at 800MB/s and then around 600MB/s
![backendb_mem](https://cloud.githubusercontent.com/assets/360884/20206463/dc852a7e-a823-11e6-990e-160d5c3f78c4.png)

At later part, client received server overloaded messages and thus throttle
```
...
Server Overloaded, Sleep 500 ms and Retry
...
```

**Comment by windkit** [comment]
After loading the 4mil image dataset, each storage node holds 2.5mil objects and metadata disk usage is around 200MB

```
$ du -sh /dev/shm/metadata
200M    /dev/shm/metadata
```

**Comment by mocchira** [comment]
@windkit in my experiences leveldb's compaction is likey to cause this kind of stop the world(STW) stall.
you can check leveldb's compaction status using https://github.com/basho/eleveldb/blob/2.0.33/src/eleveldb.erl#L258
pass a db handle to the 1st arg and "leveldb.stats" to the 2nd according to https://github.com/basho/leveldb/blob/2.0.33/db/db_impl.cc#L2113-L2135 .

https://github.com/leo-project/leo_backend_db/blob/develop/src/leo_backend_db_server.erl#L306-L309
Now leo_backend_db for ets only support `status` so also supporting leveldb by using the above stats would be the first step to further dig into.

**Comment by windkit** [comment]
@mocchira Thanks for the comment, I will test it today

**Comment by windkit** [comment]
## LeoFS's LevelDB Settings seem to be too conservative
### Description
To begin with, I checked `eleveldb` and `leveldb` projects for clues.

At [basho/leveldb](https://github.com/basho/leveldb), the team suggests settings as they have modified the compaction process over the upstream.

Therefore I decided to compare the results of different parameters.

### Methodology
`leo_backend_db_eleveldb` sets several parameters at `eleveldb:open`
(https://github.com/leo-project/leo_backend_db/blob/develop/src/leo_backend_db_eleveldb.erl#L58)
1. Write Buffer Size: 256KB ~ 3MB [random(?!)]
2. Max Open Files: 32
3. Cache Size: 64MB *(Such Option Not Found)*
4. Block Size: 10KB *(Deprecated, sst_block_size Instead)*

defaults for `basho/leveldb`
(https://github.com/basho/leveldb/blob/develop/util/options.cc#L28)
1. Write Buffer Size: 60MB
2. Max Open File: 1000
3. SST Block Size: 4KB

### Results
#### `leo_backend_db_eleveldb` defaults
![grafana_leofs](https://cloud.githubusercontent.com/assets/360884/21255104/2bf8f8ac-c3ad-11e6-8f4b-5180cf9f7ed2.png)

#### `eleveldb` (`leveldb`) defaults
![grafana_def](https://cloud.githubusercontent.com/assets/360884/21255103/2bf46fbc-c3ad-11e6-9ff5-9fba442d7639.png)

**Comment by yosukehara** [comment]
@windkit Thanks for your report. I've recognized we need to be able to configure [Leveldb's configuration](https://github.com/leo-project/leo_backend_db/blob/develop/src/leo_backend_db_eleveldb.erl#L52-L57) because in the current implementation, those configurations is fixed, `hard-coding`. I'd like to ask you to implement that.

**Comment by windkit** [comment]
**Max Open File: 1000, Write Buffer Size: 60MB
![1time](https://cloud.githubusercontent.com/assets/360884/21492562/343aaf70-cc49-11e6-9be0-56940294f315.png)

**Max Open File: 10000, Write Buffer Size: 600MB
![10times](https://cloud.githubusercontent.com/assets/360884/21492553/1db60ea2-cc49-11e6-9ff5-c2a26f3e6aee.png)

The results are similar despite of the 10x difference in parameters, there could be other bottlenecks or we need to dig down into more details

**Comment by mocchira** [comment]
Monitoring how GC in leveldb actually works using eleveldb:status may be helpful to find out where the bottleneck is and also
tuning I/O related settings in OS like described at http://docs.basho.com/riak/kv/2.2.0/setup/planning/backend/leveldb/#configuring-eleveldb may give further performance improvement
if you want more performance. (IMHO already reached a minimum requirement)

**Comment by windkit** [comment]
![fadvise](https://cloud.githubusercontent.com/assets/360884/21493444/d895be8e-cc4e-11e6-92e4-42f78ed33fc9.png)
Setting the `{fadvise_willneed, true}` actually helps to overcome the IO spikes by using the fadvise hint. Yet the throttling still occurs from time to time, it is observed that client would get error 503.
And in `leo_storage` there are many queued put requests.

I will follow up the issue after 1.3.1 release.

**Comment by windkit** [comment]
PR for fadvise_willneed in eleveldb
https://github.com/leo-project/leo_backend_db/pull/16
